//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEdition
    {
        public int EditionId { get; set; }
        public int EventId { get; set; }
        public string NomEdition { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public Nullable<System.DateTime> DateFin { get; set; }
        public string Actif { get; set; }
        public string Statut { get; set; }
        public string EventPhoto1 { get; set; }
        public string EventPhoto2 { get; set; }
        public string EventPhoto3 { get; set; }
        public string EventPhoto4 { get; set; }
        public string TextPhoto1 { get; set; }
        public string TextPhoto2 { get; set; }
        public string TextPhoto3 { get; set; }
        public string TextPhoto4 { get; set; }
    
        public virtual AspNetEvent AspNetEvent { get; set; }
    }
}
