//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AspNetEvent()
        {
            this.AspNetEditions = new HashSet<AspNetEdition>();
        }
    
        public int EventId { get; set; }
        public string UserId { get; set; }
        public string NomEvent { get; set; }
        public string Organisateur { get; set; }
        public string TypeBD { get; set; }
        public string NomServeur { get; set; }
        public string NomBD { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
        public string Statut { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetEdition> AspNetEditions { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
