// <auto-generated />
namespace PerformanteSolutionAPPUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fullname : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fullname));
        
        string IMigrationMetadata.Id
        {
            get { return "202107081801520_fullname"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
